POST http://localhost:5058/breakfast
Content-Type: application/json

// make sure you oleave a space between the header and the body
{

   "name": "V",
   "description": "",
   "startDateTime": "2022-04-08T08:00:00",
   "endDateTime": "2022-04-08T11:00:00",
   "savory": [
      "Oatmeal",
      "Avocado Toast", 
      "Omelette", 
      "Salad"
      ],
   "Sweet": [
      "Cookie"
      ]

}   

###
GET http://localhost:5058/Breakfast/99c57f9e-b8e1-47a8-8440-fccf453b6ed0